# Generated by Django 6.0.1 on 2026-01-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joint_type', models.CharField(default='butt_joint', max_length=64)),
                ('score', models.IntegerField()),
                ('grade', models.CharField(blank=True, default='', max_length=32)),
                ('captured_at', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
