# Generated by Django 4.2.9 on 2026-01-13 08:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_dataset_test_split_dataset_train_split_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rubric_type', models.CharField(choices=[('iso_5817', 'ISO 5817 Welding Quality'), ('aws_d1_1', 'AWS D1.1 Structural Welding'), ('custom', 'Custom Rubric')], default='custom', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Active rubric for evaluations')),
                ('passing_score', models.FloatField(default=3.0, help_text='Minimum average score to pass (1-5 scale)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one rubric can be active')),
                ('weight_reinforcement_height', models.FloatField(default=20.0, help_text='Weight for reinforcement height (1-3mm range)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_bead_width', models.FloatField(default=15.0, help_text='Weight for bead width (8-12mm range)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_undercut', models.FloatField(default=15.0, help_text='Weight for undercut depth', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_hi_lo', models.FloatField(default=10.0, help_text='Weight for hi-lo misalignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_porosity', models.FloatField(default=20.0, help_text='Weight for porosity defects', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_spatter', models.FloatField(default=10.0, help_text='Weight for spatter defects', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_slag_inclusion', models.FloatField(default=5.0, help_text='Weight for slag inclusion defects', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_burn_through', models.FloatField(default=5.0, help_text='Weight for burn-through defects', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('height_min', models.FloatField(default=1.0, help_text='Minimum acceptable height (mm)')),
                ('height_max', models.FloatField(default=3.0, help_text='Maximum acceptable height (mm)')),
                ('width_min', models.FloatField(default=8.0, help_text='Minimum acceptable width (mm)')),
                ('width_max', models.FloatField(default=12.0, help_text='Maximum acceptable width (mm)')),
                ('undercut_max', models.FloatField(default=0.5, help_text='Maximum acceptable undercut (mm)')),
                ('hi_lo_max', models.FloatField(default=0.3, help_text='Maximum acceptable hi-lo (mm)')),
                ('porosity_threshold', models.IntegerField(default=3, help_text='Max acceptable porosity count')),
                ('spatter_threshold', models.IntegerField(default=5, help_text='Max acceptable spatter count')),
                ('slag_threshold', models.IntegerField(default=2, help_text='Max acceptable slag inclusion count')),
                ('burn_through_threshold', models.IntegerField(default=0, help_text='Max acceptable burn-through count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(blank=True, help_text='Instructor/Evaluator name', max_length=200)),
                ('total_score', models.FloatField(default=0, help_text='Weighted average score (1-5)')),
                ('passed', models.BooleanField(default=False)),
                ('session_start', models.DateTimeField(blank=True, null=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('ai_metrics', models.JSONField(blank=True, help_text='AI-detected metrics from vision system', null=True)),
                ('notes', models.TextField(blank=True, help_text='Evaluator notes/comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='rubrics.assessmentrubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Criterion name (e.g., Bead Appearance)', max_length=200)),
                ('category', models.CharField(choices=[('geometric', 'Geometric (Dimensional)'), ('visual', 'Visual Inspection'), ('technique', 'Welding Technique'), ('safety', 'Safety & Procedure')], default='visual', max_length=50)),
                ('weight', models.FloatField(default=1.0, help_text='Weight multiplier for this criterion', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)])),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('score_1_label', models.CharField(default='Poor', max_length=50)),
                ('score_1_description', models.TextField(blank=True, help_text='Description for score 1')),
                ('score_2_label', models.CharField(default='Below Average', max_length=50)),
                ('score_2_description', models.TextField(blank=True, help_text='Description for score 2')),
                ('score_3_label', models.CharField(default='Acceptable', max_length=50)),
                ('score_3_description', models.TextField(blank=True, help_text='Description for score 3')),
                ('score_4_label', models.CharField(default='Good', max_length=50)),
                ('score_4_description', models.TextField(blank=True, help_text='Description for score 4')),
                ('score_5_label', models.CharField(default='Excellent', max_length=50)),
                ('score_5_description', models.TextField(blank=True, help_text='Description for score 5')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='rubrics.assessmentrubric')),
            ],
            options={
                'ordering': ['rubric', 'order', 'name'],
                'unique_together': {('rubric', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, help_text='Notes for this criterion')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rubrics.rubriccriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='rubrics.studentevaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'criterion')},
            },
        ),
    ]
