# Generated by Django 5.2.10 on 2026-01-14 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '__first__'),
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevaluation',
            name='assessment',
            field=models.ForeignKey(blank=True, help_text='Reference to assessment with images', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='results.assessment'),
        ),
    ]
