# Generated by Django 4.2.9 on 2026-01-12 23:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructor', models.CharField(blank=True, help_text='Instructor/Lecturer name', max_length=200)),
                ('semester', models.CharField(blank=True, help_text='e.g., Spring 2026', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StereoCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('image_width', models.IntegerField(default=1280, validators=[django.core.validators.MinValueValidator(640), django.core.validators.MaxValueValidator(3840)])),
                ('image_height', models.IntegerField(default=720, validators=[django.core.validators.MinValueValidator(480), django.core.validators.MaxValueValidator(2160)])),
                ('board_width', models.IntegerField(default=9, help_text='Chessboard width (inner corners)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
                ('board_height', models.IntegerField(default=6, help_text='Chessboard height (inner corners)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
                ('square_size_mm', models.FloatField(default=25.0, help_text='Chessboard square size in mm', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('calibration_data', models.JSONField(blank=True, help_text='Calibration parameters (Q, maps, etc.)', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Active calibration configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classgroup')),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
    ]
