# Generated by Django 5.2.10 on 2026-01-15 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataset_test_split_dataset_train_split_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Session name (e.g., 2:2025/2026)', max_length=50, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Currently active session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-name'],
            },
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='semester',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='department',
            field=models.CharField(blank=True, help_text='Department/Jabatan (e.g., JKM)', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, help_text='Department/Jabatan (e.g., JKM)', max_length=100),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(help_text='Home class name (e.g., DKM5A)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(blank=True, help_text="Student's home class (e.g., DKM5A)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Registration number (e.g., 05DKM23F2014)', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., DJJ40173)', max_length=20)),
                ('name', models.CharField(help_text='Course name (e.g., ENGINEERING DESIGN)', max_length=200)),
                ('section', models.CharField(blank=True, help_text='Section (e.g., S3)', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, help_text='Course instructor', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Academic session', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.session')),
            ],
            options={
                'ordering': ['code', 'section'],
                'unique_together': {('code', 'section', 'session')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses the student is enrolled in', related_name='enrolled_students', to='core.course'),
        ),
    ]
