# Generated by Django 5.2.13 on 2026-04-20 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_remove_classgroup_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='annotation',
            name='defect_class',
            field=models.ForeignKey(help_text='Defect class for this annotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='core.defectclass'),
        ),
    ]
