# Generated by Django 6.0.1 on 2026-01-12 02:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(help_text='YOLOv8 model file (.bin, .pt, or .onnx)', upload_to='models/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin', 'pt', 'onnx'])])),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('deployed', 'Deployed'), ('inactive', 'Inactive'), ('testing', 'Testing')], default='uploaded', max_length=20)),
                ('is_deployed', models.BooleanField(default=False, help_text='Is this model currently deployed on RDK X5?')),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy percentage', null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_to_device', models.CharField(blank=True, help_text='RDK X5 device ID where deployed', max_length=100)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('training_dataset', models.CharField(blank=True, max_length=200)),
                ('framework_version', models.CharField(blank=True, help_text='YOLOv8/PyTorch version', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mlops_aimod_created_770860_idx'), models.Index(fields=['status', 'is_deployed'], name='mlops_aimod_status_b018cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.GenericIPAddressField()),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('log_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('username', models.CharField(max_length=100)),
                ('transfer_method', models.CharField(default='scp', help_text='Transfer method (scp, sftp, etc.)', max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_logs', to='mlops.aimodel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MLJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('train', 'Train'), ('export', 'Export/Convert')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('command', models.JSONField(blank=True, default=list)),
                ('artifact_path', models.TextField(blank=True)),
                ('stdout_path', models.TextField(blank=True)),
                ('stderr_path', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_by_jobs', to='mlops.aimodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'status', '-created_at'], name='mlops_mljob_job_typ_f3ee56_idx')],
            },
        ),
    ]
