# Generated by Django 5.2.13 on 2026-04-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='file_size_mb',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='training_dataset',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='training_date',
        ),
        migrations.AlterField(
            model_name='mljob',
            name='job_type',
            field=models.CharField(choices=[('export', 'Export/Convert')], max_length=20),
        ),
    ]
